# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mrremrem/CLionProjects/OpenVillage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mrremrem/CLionProjects/OpenVillage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrremrem/CLionProjects/OpenVillage/CMakeFiles /home/mrremrem/CLionProjects/OpenVillage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrremrem/CLionProjects/OpenVillage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenVillage

# Build rule for target.
OpenVillage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenVillage
.PHONY : OpenVillage

# fast build rule for target.
OpenVillage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/build
.PHONY : OpenVillage/fast

Animation.o: Animation.cpp.o
.PHONY : Animation.o

# target to build an object file
Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Animation.cpp.o
.PHONY : Animation.cpp.o

Animation.i: Animation.cpp.i
.PHONY : Animation.i

# target to preprocess a source file
Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Animation.cpp.i
.PHONY : Animation.cpp.i

Animation.s: Animation.cpp.s
.PHONY : Animation.s

# target to generate assembly for a file
Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Animation.cpp.s
.PHONY : Animation.cpp.s

CollisionBox.o: CollisionBox.cpp.o
.PHONY : CollisionBox.o

# target to build an object file
CollisionBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/CollisionBox.cpp.o
.PHONY : CollisionBox.cpp.o

CollisionBox.i: CollisionBox.cpp.i
.PHONY : CollisionBox.i

# target to preprocess a source file
CollisionBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/CollisionBox.cpp.i
.PHONY : CollisionBox.cpp.i

CollisionBox.s: CollisionBox.cpp.s
.PHONY : CollisionBox.s

# target to generate assembly for a file
CollisionBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/CollisionBox.cpp.s
.PHONY : CollisionBox.cpp.s

DebugLog.o: DebugLog.cpp.o
.PHONY : DebugLog.o

# target to build an object file
DebugLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/DebugLog.cpp.o
.PHONY : DebugLog.cpp.o

DebugLog.i: DebugLog.cpp.i
.PHONY : DebugLog.i

# target to preprocess a source file
DebugLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/DebugLog.cpp.i
.PHONY : DebugLog.cpp.i

DebugLog.s: DebugLog.cpp.s
.PHONY : DebugLog.s

# target to generate assembly for a file
DebugLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/DebugLog.cpp.s
.PHONY : DebugLog.cpp.s

Entity.o: Entity.cpp.o
.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i
.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s
.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EntityManager.o: EntityManager.cpp.o
.PHONY : EntityManager.o

# target to build an object file
EntityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/EntityManager.cpp.o
.PHONY : EntityManager.cpp.o

EntityManager.i: EntityManager.cpp.i
.PHONY : EntityManager.i

# target to preprocess a source file
EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/EntityManager.cpp.i
.PHONY : EntityManager.cpp.i

EntityManager.s: EntityManager.cpp.s
.PHONY : EntityManager.s

# target to generate assembly for a file
EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/EntityManager.cpp.s
.PHONY : EntityManager.cpp.s

FontContainer.o: FontContainer.cpp.o
.PHONY : FontContainer.o

# target to build an object file
FontContainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/FontContainer.cpp.o
.PHONY : FontContainer.cpp.o

FontContainer.i: FontContainer.cpp.i
.PHONY : FontContainer.i

# target to preprocess a source file
FontContainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/FontContainer.cpp.i
.PHONY : FontContainer.cpp.i

FontContainer.s: FontContainer.cpp.s
.PHONY : FontContainer.s

# target to generate assembly for a file
FontContainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/FontContainer.cpp.s
.PHONY : FontContainer.cpp.s

GameManager.o: GameManager.cpp.o
.PHONY : GameManager.o

# target to build an object file
GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/GameManager.cpp.o
.PHONY : GameManager.cpp.o

GameManager.i: GameManager.cpp.i
.PHONY : GameManager.i

# target to preprocess a source file
GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/GameManager.cpp.i
.PHONY : GameManager.cpp.i

GameManager.s: GameManager.cpp.s
.PHONY : GameManager.s

# target to generate assembly for a file
GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/GameManager.cpp.s
.PHONY : GameManager.cpp.s

HomeVillage.o: HomeVillage.cpp.o
.PHONY : HomeVillage.o

# target to build an object file
HomeVillage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/HomeVillage.cpp.o
.PHONY : HomeVillage.cpp.o

HomeVillage.i: HomeVillage.cpp.i
.PHONY : HomeVillage.i

# target to preprocess a source file
HomeVillage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/HomeVillage.cpp.i
.PHONY : HomeVillage.cpp.i

HomeVillage.s: HomeVillage.cpp.s
.PHONY : HomeVillage.s

# target to generate assembly for a file
HomeVillage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/HomeVillage.cpp.s
.PHONY : HomeVillage.cpp.s

Map.o: Map.cpp.o
.PHONY : Map.o

# target to build an object file
Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Map.cpp.o
.PHONY : Map.cpp.o

Map.i: Map.cpp.i
.PHONY : Map.i

# target to preprocess a source file
Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Map.cpp.i
.PHONY : Map.cpp.i

Map.s: Map.cpp.s
.PHONY : Map.s

# target to generate assembly for a file
Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Map.cpp.s
.PHONY : Map.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Player.cpp.s
.PHONY : Player.cpp.s

Sign.o: Sign.cpp.o
.PHONY : Sign.o

# target to build an object file
Sign.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Sign.cpp.o
.PHONY : Sign.cpp.o

Sign.i: Sign.cpp.i
.PHONY : Sign.i

# target to preprocess a source file
Sign.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Sign.cpp.i
.PHONY : Sign.cpp.i

Sign.s: Sign.cpp.s
.PHONY : Sign.s

# target to generate assembly for a file
Sign.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/Sign.cpp.s
.PHONY : Sign.cpp.s

SpriteSheet.o: SpriteSheet.cpp.o
.PHONY : SpriteSheet.o

# target to build an object file
SpriteSheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/SpriteSheet.cpp.o
.PHONY : SpriteSheet.cpp.o

SpriteSheet.i: SpriteSheet.cpp.i
.PHONY : SpriteSheet.i

# target to preprocess a source file
SpriteSheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/SpriteSheet.cpp.i
.PHONY : SpriteSheet.cpp.i

SpriteSheet.s: SpriteSheet.cpp.s
.PHONY : SpriteSheet.s

# target to generate assembly for a file
SpriteSheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/SpriteSheet.cpp.s
.PHONY : SpriteSheet.cpp.s

TextBox.o: TextBox.cpp.o
.PHONY : TextBox.o

# target to build an object file
TextBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextBox.cpp.o
.PHONY : TextBox.cpp.o

TextBox.i: TextBox.cpp.i
.PHONY : TextBox.i

# target to preprocess a source file
TextBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextBox.cpp.i
.PHONY : TextBox.cpp.i

TextBox.s: TextBox.cpp.s
.PHONY : TextBox.s

# target to generate assembly for a file
TextBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextBox.cpp.s
.PHONY : TextBox.cpp.s

TextureManager.o: TextureManager.cpp.o
.PHONY : TextureManager.o

# target to build an object file
TextureManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextureManager.cpp.o
.PHONY : TextureManager.cpp.o

TextureManager.i: TextureManager.cpp.i
.PHONY : TextureManager.i

# target to preprocess a source file
TextureManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextureManager.cpp.i
.PHONY : TextureManager.cpp.i

TextureManager.s: TextureManager.cpp.s
.PHONY : TextureManager.s

# target to generate assembly for a file
TextureManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TextureManager.cpp.s
.PHONY : TextureManager.cpp.s

TileInfo.o: TileInfo.cpp.o
.PHONY : TileInfo.o

# target to build an object file
TileInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TileInfo.cpp.o
.PHONY : TileInfo.cpp.o

TileInfo.i: TileInfo.cpp.i
.PHONY : TileInfo.i

# target to preprocess a source file
TileInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TileInfo.cpp.i
.PHONY : TileInfo.cpp.i

TileInfo.s: TileInfo.cpp.s
.PHONY : TileInfo.s

# target to generate assembly for a file
TileInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/TileInfo.cpp.s
.PHONY : TileInfo.cpp.s

WindowManager.o: WindowManager.cpp.o
.PHONY : WindowManager.o

# target to build an object file
WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/WindowManager.cpp.o
.PHONY : WindowManager.cpp.o

WindowManager.i: WindowManager.cpp.i
.PHONY : WindowManager.i

# target to preprocess a source file
WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/WindowManager.cpp.i
.PHONY : WindowManager.cpp.i

WindowManager.s: WindowManager.cpp.s
.PHONY : WindowManager.s

# target to generate assembly for a file
WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/WindowManager.cpp.s
.PHONY : WindowManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenVillage.dir/build.make CMakeFiles/OpenVillage.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OpenVillage"
	@echo "... Animation.o"
	@echo "... Animation.i"
	@echo "... Animation.s"
	@echo "... CollisionBox.o"
	@echo "... CollisionBox.i"
	@echo "... CollisionBox.s"
	@echo "... DebugLog.o"
	@echo "... DebugLog.i"
	@echo "... DebugLog.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EntityManager.o"
	@echo "... EntityManager.i"
	@echo "... EntityManager.s"
	@echo "... FontContainer.o"
	@echo "... FontContainer.i"
	@echo "... FontContainer.s"
	@echo "... GameManager.o"
	@echo "... GameManager.i"
	@echo "... GameManager.s"
	@echo "... HomeVillage.o"
	@echo "... HomeVillage.i"
	@echo "... HomeVillage.s"
	@echo "... Map.o"
	@echo "... Map.i"
	@echo "... Map.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Sign.o"
	@echo "... Sign.i"
	@echo "... Sign.s"
	@echo "... SpriteSheet.o"
	@echo "... SpriteSheet.i"
	@echo "... SpriteSheet.s"
	@echo "... TextBox.o"
	@echo "... TextBox.i"
	@echo "... TextBox.s"
	@echo "... TextureManager.o"
	@echo "... TextureManager.i"
	@echo "... TextureManager.s"
	@echo "... TileInfo.o"
	@echo "... TileInfo.i"
	@echo "... TileInfo.s"
	@echo "... WindowManager.o"
	@echo "... WindowManager.i"
	@echo "... WindowManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

